### ISSUE TITLE
jasminewd2: Update Jasmine from 2.1.1 to 2.2.1

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/jasminewd#17]
Jasmine is currently set to "2.1.1" (https://github.com/angular/jasminewd/blob/jasminewd2/package.json#L16). The newest version is "2.2.1". It would be nice if my Protractor tests could run the same Jasmine version as my Karma tests.

**Comment by juliemr** [comment]
We'd love to do this, but we're waiting on Jasmine to release a new version which includes a fix to their equality matchers. See https://github.com/jasmine/jasmine/issues/765

**Comment by juliemr** [comment]
Done, updated to Jasmine 2.3.1!

**Comment by donaldpipowitch** [comment]
Nice!
