### ISSUE TITLE
jasminewd2 bind `this` to `jasmine.getEnv()` instead of an empty object.

### ISSUE THREAD

**Issue by ghusse** [angular/jasminewd#22]
According to the docs, jasmine 2 bind `this` to a new empty object for each test. This object can be prepared by `beforeEach`, and then is passed to the test and `afterEach` method.

That allows to create  independent variables for each test, as described in this post: https://gist.github.com/traviskaufman/11131303

The doc explains how it is supposed to work too: http://jasmine.github.io/2.0/introduction.html#section-The_%3Ccode%3Ethis%3C/code%3E_keyword

Now, my problem is that this feature is not available in protractor: instead of being a new empty object, each test receives the jasmine environment (which is always the same).

Probably due to this code:

    var flowFinished = flow.execute(function() {
      fn.call(jasmine.getEnv(), asyncFnDone.fulfill);
    }, 'Run ' + fnName + ' in control flow');

It is a very important feature for me to be able to get a new object on each test, it allows me to prepare the platform independently for each test (and in the future, run tests in parallel).

Is there a way to fix this?

**Comment by ghusse** [comment]
If I understand the code correctly, a simple fix might be to replace the call to `jasmine.getEnv()` by a reference to `this` which corresponds to the jasmine test context.

  var flowFinished = flow.execute(function() {
    // this = jasmine test context
    fn.call(this, asyncFnDone.fulfill);
  }, 'Run ' + fnName + ' in control flow');

**Comment by ghusse** [comment]
Is it possible to review the pull request? I really need this to fully implement my tests with protractor.

Thanks

**Comment by paulintrognon** [comment]
+1, this is a bug I also noticed myself, PR seems right

**Comment by juliemr** [comment]
Finally fixed with c0f13d254966c859db22d020a5390138dbf48e64!
