### ISSUE TITLE
Decorating Jasmine's it method

### ISSUE THREAD

**Issue by sebald** [angular/jasminewd#38]
When using `global.<method>` to decorate Jasmine's public API nothing is returned. Usually Jasmine returns the spec object, as you can see in its [source code](https://github.com/jasmine/jasmine/blob/0d4c8d13bb46ef18ecbff250394582e63f7a4696/lib/jasmine-core/jasmine.js#L913-L920).

Using `jasmine.getEnv().it('test blabla', () => {})` will correctly return the spec object, but decorating this will mess up Protractor as mentioned by @juliemr in angular/protractor#2823

I am not quite sure what's the issue here. I checked the source of `jasminewd` and found that `wrapInControlFlow` does not return something, but I thought decorating the `global.it` would add my function *before* `jasminewd` decorates the tests.

---

For context: I want to add additional properties (SRS reference, custom identifier) to the spec object, so that I can create a report with information about SRS coverage etc.

Something like this:

```javascript
// In the test suite
it('SRS_ID_1', 'should test something', () => {
  expect(true).toBeTruthy();
});
```

```javascript
// Decorator
var originalIt = global.it;
global.it = function (ref, desc, fn) {
  var spec = originalIt(desc, fn);
  spec.result.ref = ref;
  return spec;
}
```

```javascript
// Reporter

var results = [];

jasmine.getEnv().addReporter({

  specDone: (result) => { results.push(result) },
  jasmineDone () => {
    // Create report
  }

});
```

**Comment by sebald** [comment]
I tried something. I do not thing is the correct way, but it works :-x

`wrapInControlFlow` return the result of the `globalFn` which is the `jasminewd` wrapper for Jasmine's spec methods (`it`, `fit`, ...).
-> https://github.com/sebald/jasminewd/commit/b1a712a5650876025c06ee11d6089f5c67bd58c3#diff-168726dbe96b3ce427e7fedce31bb0bc

Using the code from my [last comment](#issue-126368107) I can now add additional properties to the `spec.result` and display/use it in reporter.

**Comment by juliemr** [comment]
@sebald I think that that commit is actually doing the right thing. Jasminewd should wrap the functions before your code, so it needs to pass along the returned value. Can you make that into a PR?

**Comment by sjelin** [comment]
Now that I've merged in an equivalent PR is this safe to close?

**Comment by sebald** [comment]
Tested it today. Works fine for me :)

Thanks!
