### ISSUE TITLE
feat(async): support returning promises

### ISSUE THREAD

**Issue by sjelin** [angular/jasminewd#48]
Jasmine has opted not to support returning promises: https://github.com/jasmine/jasmine/issues/681

One result of this is that users can't take advantage of async functions 😢 

We should just support async functions ourselves.  Our users want it (https://github.com/angular/protractor/issues/1214) and it seems like the way of the future.

Thoughts @juliemr @cnishina @mgiambalvo ?

**Comment by mgiambalvo** [comment]
Well, I think it's lame that they don't want to support returning promises.
I agree we should find a way to support async functions. If there's a well
supported plugin (maybe jasmine-promises
<https://www.npmjs.com/package/jasmine-promises>?), then we should probably
just use that and make it our "official" solution for doing async tests.

**Comment by sjelin** [comment]
The plugin is a bit weird because you have to include it as a spec.  Also, we can use our existing infrastructure around async functions to implement this in ~10 lines - much smaller than including a whole new plugin.

**Comment by mattburrell** [comment]
@sjelin async function support would be an awesome feature. Any idea of when it might become available?

**Comment by sjelin** [comment]
This is already available, as of PR #49.  I expected merging that PR to automatically close this issue but I guess not.  If I recall correctly, I discovered upon further investigation that the functionality was there the whole time and nothing needed to be done.
